# Generated by Django 6.0.4 on 2026-05-25 17:50

import questions.models
from django.db import migrations, models


def ensure_profile_table(apps, schema_editor):
    table_names = schema_editor.connection.introspection.table_names()
    if 'questions_profile' in table_names:
        return
    Profile = apps.get_model('questions', 'Profile')
    schema_editor.create_model(Profile)


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_alter_answer_options_alter_answerlike_options_and_more'),
    ]

    operations = [
        migrations.RunPython(ensure_profile_table, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=questions.models.profile_avatar_path, verbose_name='Аватар'),
        ),
    ]
