# Generated by Django 6.0.4 on 2026-05-24 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_alter_answer_options_alter_answerlike_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='text',
            field=models.TextField(max_length=4000, verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='question',
            name='text',
            field=models.TextField(max_length=4000, verbose_name='Текст'),
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
