worker_processes 1;
error_log stderr notice;
pid /tmp/nginx.pid;

events { worker_connections 1024; }

http {
  include       mime.types;
  default_type  application/octet-stream;
  sendfile on;
  gzip on;
  gzip_types text/plain text/css application/json application/javascript text/xml application/xml application/xml+rss text/javascript;

  proxy_cache_path /tmp/nginx_cache levels=1:2 keys_zone=cache_zone:10m max_size=100m inactive=1h use_temp_path=off;

  upstream askme_upstream { server 127.0.0.1:8000; }

  server {
    listen 80;
    server_name localhost;

    location ^~ /uploads/ {
      alias /Users/ikuba46/VK Education/1 Term/WebDev/2026-VK-EDU-Web-11-Krivetskiy-A/ask_krivetskiy/uploads/;
      expires 30d;
      add_header Cache-Control "public";
    }

    location ~* \.(css|js|jpg|jpeg|png|gif|webp|svg|ico|html)$ {
      alias /Users/ikuba46/VK Education/1 Term/WebDev/2026-VK-EDU-Web-11-Krivetskiy-A/ask_krivetskiy/static/;
      expires 30d;
      add_header Cache-Control "public";
    }

    location / {
      proxy_pass http://askme_upstream;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_cache cache_zone;
      proxy_cache_valid 200 10m;
      add_header X-Cache-Status $upstream_cache_status;
    }
  }
}
